name: Python linting and e2e tests

on:
  push:
    branches: [main]
    paths: ["instagram/**", "tests/**"]
  pull_request:
    branches: [main]
    paths: ["instagram/**", "tests/**"]

permissions:
  contents: read

jobs:
  ruff:
    name: Lint and Format Python Client (Ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.4"
          args: check --output-format=github
          # src: "./instagram"

      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.12.4"
          args: format --check --diff
          # src: "./instagram"
  test:
    name: Test Python Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Add the Python versions you want to test

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/test.py
