name: TypeScript linting and e2e tests

# Only triggers on changes to the TypeScript codebase
on:
  push:
    branches:
      - main
    paths:
      - "instagram-ts/**"
  pull_request:
    branches:
      - main
    paths:
      - "instagram-ts/**"

jobs:
  format:
    name: Lint and Test TypeScript Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install TS dependencies
        working-directory: instagram-ts
        run: |
          npm ci

      - name: Run Prettier check
        working-directory: instagram-ts
        run: npx prettier --check .

      - name: Run xo + tests
        working-directory: instagram-ts
        run: npm test
